### ISSUE TITLE
Q: where does miniconda come from?

### ISSUE THREAD

**Issue by yarikoptic** [vsoch/datalad-action#11]
Dear @vsoch -- thanks again for bootstrapping datalad-action.

Looking at 
```
# Ensure git annex added to path
# Datalad needs to be installed to this conda environment
echo "/usr/share/miniconda/bin" >> ${GITHUB_PATH}
export PATH="/usr/share/miniconda/bin:$PATH"
which pip
```

where did miniconda come from? datalad-installer was not asked to install it, so is it coming by default there on ubuntu envs?  do you know where it is on macos, since in #10 it failed with

```
ls: /usr/share/miniconda/bin: No such file or directory
423
Error: Process completed with exit code 1.```

**Comment by vsoch** [comment]
You can always see the guts of the runner in these repos, e.g., here is the answer to your question:
https://github.com/actions/runner-images/blob/main/images/linux/Ubuntu2204-Readme.md#environment-variables

I didn't see why a Mac runner would be needed, so I assumed Linux (ubuntu base).

**Comment by yarikoptic** [comment]
Coolio, thank you! So we can just use CONDA environment variable for the location, I will try that
