### ISSUE TITLE
github action for datalad-osf

### ISSUE THREAD

**Issue by hvgazula** [vsoch/datalad-action#18]
**Is your feature request related to a problem? Please describe.**
I just found out there's a github action available for installing datalad. However, my storage siblings are on OSF meaning, I need to install datalad-osf as well. Currently, I do this by `pip install datalad-osf`. 

**Proposed solution & alternatives considered**
While I am not an expert in github actions, I was curious if there are any thoughts of creating an action for datalad-osf as well.

**Comment by yarikoptic** [comment]
do you mean like adding `pip install datalad-osf` to accompany installation of `datalad` in `datalad-action` before it tries to fetch any data from OSF? then we better do it in https://github.com/datalad/datalad-action , right?

**Comment by hvgazula** [comment]
Yes, by providing it as an option with a True or False flag along with datalad installation (as not every user may need the osf part).

**Comment by yarikoptic** [comment]
ok, let's move there and I am looking into addressing it but rather a little differently  (to gain any generic `pip install`) in https://github.com/datalad/datalad-action/pull/17

**Comment by yarikoptic** [comment]
I have merged #17 so you can try using `@master` version by adding `with` `pip_install: datalad-osf`

**Comment by hvgazula** [comment]
worked smoothly..thank you very much.

**Comment by hvgazula** [comment]
Hi @yarikoptic Sorry to bother you again. This action works fine in a GitHub runner but not a self-hosted runner on ec2. I noticed this is because all actions in ec2 are run as `root`. Do you think adding `-y` flags as appropriate in the `install.sh` script will suffice? 

For context, this is the output when run on ec2. 
<img width="1007" alt="image" src="https://github.com/datalad/datalad-action/assets/9400767/8f709957-dacc-4b11-8ee9-c96764cc8572">


PS: Please ignore this request if this is not the right place to ask this question. Nevertheless, thanks once again for making `datalad-osf` available in this action.

**Comment by yarikoptic** [comment]
> This action works fine in a GitHub runner but not a self-hosted runner on ec2.

Those are not yet a familiar animal to me :-/   Please file a separate issue so we do not forget about it -- would need to check what/how we do differently between the two.  Adding an option to datalad-installer might indeed be all what is needed. IF you could try (on your personal fork) and report back or better submit a PR -- would be appreciated and expedite boiling down the solution. Myself -- I would need then first to figure out how to establish such a runner to test on ;)
