### ISSUE TITLE
keep here or move to datalad org?

### ISSUE THREAD

**Issue by yarikoptic** [vsoch/datalad-action#4]
what do you prefer? from `datalad/datalad-action/install@main` I guess it relies on being under datalad org, right?

**Comment by vsoch** [comment]
yes the action should be under datalad :)

**Comment by yarikoptic** [comment]
I have created https://github.com/datalad/datalad-action/ so you could  push there and then make this one your personal fork.

**Comment by vsoch** [comment]
It would be easier if you added me as an org member and deleted that repo and allowed me to transfer. I don't want to push new commits (and cannot during a work day) but I can move the work I did over the weekend. Does that work?

**Comment by yarikoptic** [comment]
welcome to the bright future (likely micro$oft inspired) -- tried to add you to a new team and got

```
You have no remaining seats in your organization. Please purchase at least one additional seat before inviting vsoch to DataLad.
```

had to convert some past contributors to outside to free up a "seat" and invite you to `datalad-action` team; removed that repo

**Comment by vsoch** [comment]
And you can remove me after I transfer and add as a contributor - I don't want to take a seat!

Also GitHub free is much better than paying :)

**Comment by vsoch** [comment]
@yarikoptic can you bump my permissions temporarily? I just got:

> You don’t have the permission to create public repositories on datalad

**Comment by yarikoptic** [comment]
how do I know that @vsoch github login is not possessed by some evil spirits if I do not even see the face while fingers typing? ;)

- I do not see what is the difficulty to simply adjust URL for origin and push to datalad/datalad-action if I recreate it and make you owner there?
- what if you make me Admin for this repo (only) - I should be able to move it, right?

**Comment by vsoch** [comment]
sure we can try the latter.

**Comment by vsoch** [comment]
I can't believe you don't trust me, that feels pretty shitty.

**Comment by vsoch** [comment]
I invited you to my repository. Feel free to accept at your leisure. I trust you at least.

**Comment by yarikoptic** [comment]
> I can't believe you don't trust me, that feels pretty shitty.

I do not trust someone who replies here, and not necessarily being the @vsoch I know ;)   Wanna zoom or jitsi for "confirmation"? join https://meet.jit.si/IsVsochReal? -- I will be there for a bit

having push permission seems to be not enough to reveal Settings for this repo etc.

**Comment by vsoch** [comment]
yeah I'm coming, but no camera I'm in pajamas. Because today sucks.
